global: { scrape_interval: 5s }
scrape_configs:
  - job_name: gateway
    static_configs: [{ targets: ["gateway:8080"] }]
  - job_name: user
    static_configs: [{ targets: ["user:8080"] }]
  - job_name: product
    static_configs: [{ targets: ["product:8080"] }]
  - job_name: order
    static_configs: [{ targets: ["order:8080"] }]
  - job_name: payment
    static_configs: [{ targets: ["payment:8080"] }]